import '~/styles/globals.css';

import { type Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Lingodeck',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className="flex h-full justify-center items-start p-5">
      {children}
    </main>
  );
}
