import '~/styles/globals.css';

import {
  ClerkProvider
} from '@clerk/nextjs';
import { Toaster } from '~/components/ui/sonner';
import { NavMenu } from '~/components/ui/navigation-menu';
import { Moon, MoonIcon, Sun, EllipsisVertical } from "lucide-react"
import Link from 'next/link';

import { ThemeProvider } from '../../components/theme-provider';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import { Button } from '~/components/ui/button';


export const metadata: Metadata = {
  title: 'Lingodeck',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <main className="flex h-full justify-center items-center p-5">
      {children}
    </main>
  );
}
