import '~/styles/globals.css';

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Toaster } from '~/components/ui/sonner';
import { TopNav } from '../components/ui/topnav';

import { ThemeProvider } from '../components/theme-provider';

import { GeistMono } from 'geist/font/mono';
import { type Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Lingodeck',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html className={`${GeistMono.variable}`} lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute="class"
            // defaultTheme="system"
            // enableSystem
            disableTransitionOnChange
          >
            <TopNav />
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
